config/routes.rb
Rails.application.routes.draw do

  resources :venta
  resources :productos
  resources :productos
  get    'signup'  => 'empleados#new'
  get   'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
   
  resources :empleados

 root 'dashboard#index'
 

   get 'dashboard' => 'dashboard#index'
  get 'privacidad' => 'dashboard#privacidad'
  get 'terminos' => 'dashboard#terminos'
  get 'reportes/ventas' => 'reportes#ventas'
  get 'reportes/ganancias' => 'reportes#ganancias'
end

app/controllers/venta_controller.rb
class VentaController < ApplicationController
  before_action :set_ventum, only: [:show, :edit, :update, :destroy]

  # GET /venta
  # GET /venta.json
  def index
    @venta = Ventum.all
    @venta_productos = VentaProducto.joins(:producto).all
  end

  # GET /venta/1
  # GET /venta/1.json
  def show
    # @productos = VentaProducto.find_by_ventum_id(params[:id])
  end

  # GET /venta/new
  def new
    @ventum = Ventum.new
  end

  # GET /venta/1/edit
  def edit
  end

  # POST /venta
  # POST /venta.json
  def create
    productos = JSON.parse ventum_params['productos']
    venta = ventum_params
    venta.delete('productos')
    @ventum = Ventum.new(venta)
    respond_to do |format|
      if @ventum.save
        create_all_relations(@ventum["id"],productos)
        format.html { redirect_to @ventum, notice: 'Venta Creada!' }
        format.json { render :show, status: :created, location: @ventum }
      else
        format.html { render :new }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end


  def create_all_relations(id,array)
    (array).each do |v|
      venta_producto = Hash.new
      venta_producto["producto_id"] = v["id"]
      venta_producto["ventum_id"] = id
      venta_producto["precio"] = v["precio"]
      venta_producto["cantidad"] = v["cantidad"]
      venta_producto["total"] = v["precio"] * v["cantidad"]
      if VentaProducto.new(venta_producto).save
        actualizar_inventario(venta_producto["producto_id"],venta_producto["cantidad"])
      end
    end
  end

  def actualizar_inventario(id,minus)
     producto = Producto.find(id)
     nuevos_params = Hash.new
     nuevos_params["stock"] = producto["stock"] - minus;
     producto.update(nuevos_params)
  end

  # PATCH/PUT /venta/1
  # PATCH/PUT /venta/1.json
  def update
    respond_to do |format|
      if @ventum.update(ventum_params)
        format.html { redirect_to @ventum, notice: 'Venta Actualizada' }
        format.json { render :show, status: :ok, location: @ventum }
      else
        format.html { render :edit }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venta/1
  # DELETE /venta/1.json
  def destroy
    @ventum.destroy
    respond_to do |format|
      format.html { redirect_to venta_url, notice: 'Venta Borrada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventum
      @ventum = Ventum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ventum_params
      params.require(:ventum).permit(:empleado_id, :nombre_cliente, :tipo_pago, :subtotal, :impuesto, :total, :productos)
    end
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/venta/_form.html-OLD.erb
<%= form_for(@ventum) do |f| %>
  <% if @ventum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ventum.errors.count, "error") %> prohibited this ventum from being saved:</h2>

      <ul>
      <% @ventum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :empleado %><br />
    <%= f.select :empleado_id, options_for_select(Empleado.all.map{|s|[s.nombre, s.id]}) %>
  </div>
  <div class="field">
    <%= f.label :nombre_cliente %><br>
    <%= f.text_field :nombre_cliente, class:"form-control" ,placeholder:"nombre" %>
  </div>
  <div class="field">
    <%= f.label :tipo_pago %><br>
    <%= f.select :tipo_pago, ['Tarjeta', 'Efectivo', 'T-Pago'], class:"form-control select select-primary select2-offscreen" %>
  </div>
  <div class="field">
    <%= f.label :subtotal %><br>
    <%= f.text_field :subtotal %>
  </div>
  <div class="field">
    <%= f.label :impuesto %><br>
    <%= f.text_field :impuesto %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venta/_form.html.erb
<div ng-controller="factura" ng-init="init_productos()">
<%= form_for(@ventum) do |f| %>
    <% if @ventum.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ventum.errors.count, "error") %> prohibited this ventum from being saved:</h2>

          <ul>
            <% @ventum.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-md-4">
        <h5>Datos</h5>
        <div class="field">
          <%= f.label :empleado %><br />
          <%= f.select :empleado_id, options_for_select(Empleado.all.map{|s|[s.nombre, s.id]}) %>
        </div>
        <div class="field">
          <%= f.label :nombre_cliente %><br>
          <%= f.text_field :nombre_cliente, class: "form-control", placeholder: "nombre" %>
        </div>
        <div class="field">
          <%= f.label :tipo_pago %><br>
          <%= f.select :tipo_pago, ['Tarjeta', 'Efectivo', 'T-Pago'], class: "form-control select select-primary select2-offscreen" %>
        </div>
        <div class="field">
          <%= f.text_field :subtotal, value: '{{calcular().subtotal}}', style: 'display:none' %>
        </div>
        <div class="field">
          <%= f.text_field :impuesto, value: '{{calcular().impuesto}}', style: 'display:none' %>
        </div>
        <div class="field">
          <%= f.text_field :total, value: '{{calcular().total}}', style: 'display:none' %>
        </div>
        <div class="field">
          <%= f.text_area :productos, value: '{{venta}}', style: 'display:none' %>
        </div>
        <div class="actions">
          <%= f.submit "Facturar", class: "btn btn-primary"%>
          <%= link_to 'Cancelar', venta_path, class: "btn btn-danger" %>
        </div>
      </div>
      <div class="col-md-8">
        <h5>Detalles</h5>
        <table class="table">
          <tr>
            <select ng-show="productos_validos().length > 0" ng-model="producto_a_agregar" ng-options="producto.id as producto.nombre for producto in productos_validos()"></select>
            <a class="btn btn-success btn-sm" ng-click="agregar_producto(producto_a_agregar)"><span class="glyphicon glyphicon-plus-sign"></span></a></tr>
          <thead>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Total</th>
            <th>Acciones</th>
          </thead>
          <tbody>
            <tr ng-repeat="producto in venta">
              <td>{{producto.nombre}}</td>
              <td><input type="number" ng-model="producto.cantidad" min="1" max="{{producto.stock}}"/> / {{producto.stock}}</td>
              <td>RD$ {{redondear(producto.precio)}}</td>
              <td>RD$ {{redondear(producto.precio * producto.cantidad)}}</td>
              <td><a class="btn btn-danger btn-xs" ng-click="remover_producto(producto.id)">remover</a></td>
            </tr>
          </tbody>
          <tr>
            <td><b>Subtotal: RD$ {{calcular().subtotal}}</b></td>
            <td><b>Impuesto (18%): RD$ {{calcular().impuesto}}</b></td>
            <td colspan="3" style="text-align: right"><b>Total: RD$ {{calcular().total}}</b></td>
          </tr>
        </table>
      </div>
    </div>
<% end %>
</div>

app/views/venta/edit.html.erb
<h1>Editar Venta</h1>

<%= render 'form' %>

app/views/venta/index.html.erb
<% provide(:title, "Ventas") %>
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <h3 class="col-md-12">Listado de Ventas</h3>
    <br>



    <div class="col-md-12">
      <a class="btn btn-primary btn-sm" href="/venta/new" target="_blank"><span class="glyphicon glyphicon-plus"></span> Nueva Venta</a>
    </div>

    <div class="col-md-12">
      <!-- Table -->
      <table class="table">
        <thead>
        <tr>
          <th>#</th>
          <th>Fecha</th>
          <th>Hora</th>
          <th>Nombre del empleado</th>
          <th>Nombre del cliente</th>
          <th>Tipo pago</th>
          <th>Subtotal</th>
          <th>Impuesto</th>
          <th>Total</th>
          <th style="text-align: center;">Acciones</th>
        </tr>
        </thead>

        <tbody>
        <tbody>
        <% @venta.each do |ventum| %>
            <tr>
              <td><%= ventum.id %></td>
              <td><%= ventum.created_at.strftime("%m/%d/%Y") %></td>
              <td><%= ventum.created_at.strftime("%H:%M:%S") %></td>
              <td><%= ventum.empleado.nombre %></td>
              <td><%= ventum.nombre_cliente %></td>
              <td><%= ventum.tipo_pago %></td>
              <td>RD$ <%= ventum.subtotal %></td>
              <td>RD$ <%= ventum.impuesto %></td>
              <td>RD$ <%= ventum.total %></td>
              <td><a class="btn btn-success btn-xs" href="/venta/<%= ventum.id %>"><span class="glyphicon glyphicon-shopping-cart"></span> Detalles</a></td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/venta/new.html.erb
<h3>Nueva Venta</h3>

<%= render 'form' %>

app/views/venta/show.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>

  <div class="col-md-4">
    <h5>Datos</h5>

    <p>
      <strong>Empleado:</strong>
      <a class="link" href="/empleados/<%= @ventum.empleado.id %>"><%= @ventum.empleado.nombre %></a>
    </p>

    <p>
      <strong>Nombre cliente:</strong>
      <%= @ventum.nombre_cliente %>
    </p>

    <p>
      <strong>Tipo pago:</strong>
      <%= @ventum.tipo_pago %>
    </p>

    <p>
      <strong>Fecha:</strong>
      <%= @ventum.created_at.strftime("%m/%d/%Y - %H:%M:%S") %>
    </p>

    <p>
      <strong>Subtotal:</strong>
      <%= @ventum.subtotal %>
    </p>

    <p>
      <strong>Impuesto:</strong>
      <%= @ventum.impuesto %>
    </p>

    <p>
      <strong>Total:</strong>
      <%= @ventum.total %>
    </p>
    <%= link_to '<span class="glyphicon glyphicon-th-list"></span> Volver a Lista'.html_safe, venta_path, class: "btn btn-warning" %>
  </div>
  <div class="col-md-8">
    <h5>Detalles</h5>
    <button class="btn btn-info" onclick="imprimir_factura('<%= @ventum.empleado.nombre %>','<%= @ventum.nombre_cliente %>','<%= @ventum.tipo_pago %>','<%= @ventum.created_at.strftime("%m/%d/%Y - %H:%M:%S") %>')">
      <span class="glyphicon glyphicon-print"></span> Imprimir
    </button>
    <div id="factura">
      <table class="table">
        <thead>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Precio (c/u)</th>
        <th>Total</th>
        </thead>
        <tbody>
        <% VentaProducto.all.each do |producto| %>
            <% if producto.ventum_id == @ventum.id %>
                <tr>
                  <td><a class="link" href="/productos/<%= producto.producto.id %>"><%= producto.producto.nombre %></a>
                  </td>
                  <td><%= producto.cantidad %></td>
                  <td><%= producto.precio %></td>
                  <td><%= producto.total %></td>
                </tr>
            <% end %>
        <% end %>
        </tbody>
        <tr>
          <td><b>Subtotal: RD$ <%= @ventum.subtotal %></b></td>
          <td><b>Impuesto (18%): RD$ <%= @ventum.impuesto %></b></td>
          <td colspan="3" style="text-align: right"><b>Total: RD$ <%= @ventum.total %></b></td>
        </tr>
      </table>
    </div>
  </div>

</div>