config/routes.rb
Rails.application.routes.draw do

  resources :venta
  resources :productos
  resources :productos
  get    'signup'  => 'empleados#new'
  get   'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
   
  resources :empleados

 root 'dashboard#index'
 

   get 'dashboard' => 'dashboard#index'
  get 'privacidad' => 'dashboard#privacidad'
  get 'terminos' => 'dashboard#terminos'
  get 'reportes/ventas' => 'reportes#ventas'
  get 'reportes/ganancias' => 'reportes#ganancias'
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  
   has_secure_password

 # Returns the hash digest of the given string.
  def Empleado.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    #respond_to do |format|
      if @empleado.save
         log_in @empleado
         flash[:success] = "Welcome to the site!"
      redirect_to root_url
       # format.html { redirect_to @empleado, notice: 'Empleado was successfully created.' }
        #format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: 'Empleado Actualizado.' }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: 'Empleado Borrado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nombre, :password, :password_confirmation, :posicion, :sueldo)
    end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_form.html.erb
<%= form_for(@empleado) do |f| %>
  <% if @empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
      <% @empleado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, class:"form-control" ,placeholder:"nombre" %>
  </div>
  <div class="field">
    <%= f.label :password, value:"contraseña" %><br>
    <%= f.password_field :password, class:"form-control" ,placeholder:"contrasena" %>
  </div>
<div class="field">
    <%= f.label :password_confirmation, value:"confirmacion de contraseña" %><br>
    <%= f.password_field :password_confirmation, class:"form-control" ,placeholder:"contrasena" %>
  </div>
  <div class="field">
    <%= f.label :posicion %><br>
    <%= f.select :posicion, ['Administrador', 'Vendedor', 'Encargado de Almacen'], class:"form-control select select-primary select2-offscreen" %>
  </div>
  <div class="field">
    <%= f.label :sueldo %><br>
    <%= f.number_field :sueldo, class:"form-control" ,placeholder:"sueldo" %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar", class: "btn btn-primary"%>
    <%= link_to 'Cancelar', empleados_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h3>Editar Empleado</h3>

<%= render 'form' %>

app/views/empleados/index.html.erb
<% provide(:title, "Empleados") %>
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <h3 class="col-md-12">Listado de Empleados</h3>
    <br>



    <div class="col-md-12">
      <a class="btn btn-primary btn-sm" href="/empleados/new"><span class="glyphicon glyphicon-plus"></span> Nuevo Empleado</a>
    </div>

    <div class="col-md-12">
      <!-- Table -->
      <table class="table">
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Posicion</th>
          <th>Sueldo</th>
          <th colspan="3" style="text-align: center;">Acciones</th>
        </tr>
        </thead>

        <tbody>
        <% @empleados.each do |empleado| %>
            <tr>
              <td><%= empleado.nombre %></td>
              <td><%= empleado.posicion %></td>
              <td>$ <%= empleado.sueldo %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-eye-open"></span> Mostrar'.html_safe, empleado, class: "btn btn-info btn-xs" %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-edit"></span> Editar'.html_safe, edit_empleado_path(empleado), class: "btn btn-success btn-xs" %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-trash"></span> Borrar'.html_safe, empleado, method: :delete, data: {confirm: 'Estas seguro?'}, class: "btn btn-danger btn-xs" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/empleados/new.html.erb
<h3>Nuevo Empleado</h3>

<%= render 'form' %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @empleado.nombre %>
</p>

<p>
  <strong>Posicion:</strong>
  <%= @empleado.posicion %>
</p>

<p>
  <strong>Sueldo:</strong>
  <%= @empleado.sueldo %>
</p>

<%= link_to '<span class="glyphicon glyphicon-edit"></span> Editar'.html_safe, edit_empleado_path(@empleado), class: "btn btn-primary" %> |
<%= link_to '<span class="glyphicon glyphicon-th-list"></span> Volver a Lista'.html_safe, empleados_path, class: "btn btn-warning" %> |
<%= link_to '<span class="glyphicon glyphicon-trash"></span> Borrar'.html_safe, @empleado, method: :delete, data: {confirm: 'Estas seguro?'}, class: "btn btn-danger" %>