config/routes.rb
Rails.application.routes.draw do

  resources :venta
  resources :productos
  resources :productos
  get    'signup'  => 'empleados#new'
  get   'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
   
  resources :empleados

 root 'dashboard#index'
 

   get 'dashboard' => 'dashboard#index'
  get 'privacidad' => 'dashboard#privacidad'
  get 'terminos' => 'dashboard#terminos'
  get 'reportes/ventas' => 'reportes#ventas'
  get 'reportes/ganancias' => 'reportes#ganancias'
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  has_many :venta_productos
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto Creado!' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto Actualizado' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto Destruido' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :descripcion, :costo, :precio, :stock, :categoria, :bodega)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, class:"form-control" ,placeholder:"nombre" %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion, class:"form-control" ,placeholder:"descripcion" %>
  </div>
  <div class="field">
    <%= f.label :costo %><br>
    <%= f.text_field :costo, class:"form-control" ,placeholder:"costo" %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio, class:"form-control" ,placeholder:"precio" %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock, class:"form-control" ,placeholder:"stock" %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.select :categoria, ['Acidificantes Urinarios','Analgésicos','Andrógenos','Anestésicos','Anorexígenos','Antiácidos','Antiacnéicos','Antiadrenales','Antianginosos','Antiarrítmicos','Antiartríticos','Antiartrósicos','Antiasmáticos','Antibacterianos','Anticoagulantes','Anticolelitiásicos','Anticonceptivos','Anticonvulsivantes','Antidiarréicos','Antidisquinéticos','Antidiuréticos','Antídotos','Antieméticos','Antiespasmódicos','Antiespásticos','Antifibróticos','Antiflatulentos','Antifúngicos','Antiglaucomatosos','Antigotosos','Antigripales','Antihelmínticos','Antihemorrágicos','Antihemorroidales','Antihipercalcémicos','Antihipercolesterolémicos','Antihiperlipémicos','Antihiperoxalúricos','Antihiperpotasémicos','Antihiperprolactémicos','Antihipertensivos','Antihipertiroidales','Antihiperuricémicos','Antihipocalcémicos','Antihipocolesterolemiantes','Antihipotensivos','Antihistamínicos','Antiinflamatorios','Antijaquecosos','Antileprosos','Antilitiásicos','Antimaláricos','Antimiasténicos','Antimicóticos','Antineoplásicos','Antirreumáticos','Antisárnicos','Antiseborréicos','Antisépticos','Antitiroideos','Antituberculosos','Antitusivos','Antiulcerosos','Antiurolitiásicos','Antivaricosos','Antivertiginosos','Antivirales','Bloqueadores Neuromusculares','Broncodilatadores','Capilaroprotectores','Cardiotónicos','Ciclopléjicos','Citotóxicos','Colelitolíticos','Cosméticos','Descongestionantes','Diuréticos','Eméticos','Escabicidas','Esteroides','Estimulantes Motilidad Gástrica','Estimulantes S.N.C.','Germicidas','Hipocolesterolemiantes','Hipoglicemiantes','Hipolipemiantes','Hormonas','Inhibidores Dopaminérgicos','Inhibidores Gonadotróficos','Inhibidores Parto','Inhibidores Secreciones Gástricas','Inmunosupresores','Laxantes','Midriáticos','Mielodepresores','Mióticos','Mucolíticos','Orexígenos','Oxitócicos','Pediculicidas','Placebos','Profilácticos','Protectores Radiaciones',], class:"form-control select select-primary select2-offscreen" %>
  </div>
  <div class="field">
    <%= f.label :bodega %><br>
    <%= f.select :bodega, ['A-1', 'A-2', 'A-3','B-1', 'B-2', 'B-3','C-1', 'C-2', 'C-3'], class:"form-control select select-primary select2-offscreen" %>
  </div>
    <div class="actions">
      <%= f.submit "Enviar", class: "btn btn-primary"%>
      <%= link_to 'Cancelar', productos_path, class: "btn btn-danger" %>
    </div>
<% end %>

app/views/productos/edit.html.erb
<h3>Editar Producto</h3>

<%= render 'form' %>

app/views/productos/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <h3 class="col-md-12">Listado de Productos</h3>
    <br>

    <div class="col-md-12">
      <a class="btn btn-primary btn-sm" href="/productos/new"><span class="glyphicon glyphicon-plus"></span> Nuevo Producto</a>
    </div>
    <br>
    <div class="col-md-12">
      <!-- Table -->
      <table class="table">
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Descripcion</th>
          <th>Costo (c/u)</th>
          <th>Precio (c/u)</th>
          <th>Stock</th>
          <th>Categoria</th>
          <th>Bodega</th>
          <th colspan="3" style="text-align: center">Acciones</th>
        </tr>
        </thead>

        <tbody>
        <% @productos.each do |producto| %>
            <tr>
              <td><%= producto.nombre %></td>
              <td><%= producto.descripcion %></td>
              <td>RD$ <%= producto.costo %></td>
              <td>RD$ <%= producto.precio %></td>
              <td><%= producto.stock %> unidades</td>
              <td><%= producto.categoria %></td>
              <td><%= producto.bodega %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-eye-open"></span> Mostrar'.html_safe, producto, class: "btn btn-info btn-xs" %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-edit"></span> Editar'.html_safe, edit_producto_path(producto), class: "btn btn-success btn-xs" %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-trash"></span> Borrar'.html_safe, producto, method: :delete, data: {confirm: 'Estas seguro?'}, class: "btn btn-danger btn-xs" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/productos/new.html.erb
<h3>Nuevo Producto</h3>

<%= render 'form' %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @producto.costo %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @producto.stock %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @producto.categoria %>
</p>

<p>
  <strong>Bodega:</strong>
  <%= @producto.bodega %>
</p>

<%= link_to '<span class="glyphicon glyphicon-edit"></span> Editar'.html_safe, edit_producto_path(@producto), class: "btn btn-primary"  %> |
<%= link_to '<span class="glyphicon glyphicon-th-list"></span> Volver a Lista'.html_safe, productos_path, class: "btn btn-warning"  %> |
<%= link_to '<span class="glyphicon glyphicon-trash"></span> Borrar'.html_safe, @producto, method: :delete, data: {confirm: 'Estas seguro?'}, class: "btn btn-danger" %>