config/routes.rb
Rails.application.routes.draw do

  resources :venta
  resources :productos
  resources :productos
  get    'signup'  => 'empleados#new'
  get   'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
   
  resources :empleados

 root 'dashboard#index'
 

   get 'dashboard' => 'dashboard#index'
  get 'privacidad' => 'dashboard#privacidad'
  get 'terminos' => 'dashboard#terminos'
  get 'reportes/ventas' => 'reportes#ventas'
  get 'reportes/ganancias' => 'reportes#ganancias'
end

app/views/layouts/_header.html.erb
<div>
  <%= link_to "Log out", logout_path, method: "delete" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="ventas">
<head>
  <title>Farmax | Sistema</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
    <nav class="navbar navbar-inverse navbar-embossed" id="fullNavbar">
      <div class="container">
        <div>
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>

            </button>
            <div id="logo">
              <a class="navbar-brand" href="/">FARMAX</a>
              <%= image_tag("redcross2.png", :alt => "rss feed") %>
            </div>

          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
              <li class="<%= 'active' if params[:controller] == 'dashboard' %>"><a href="/"><span class="glyphicon glyphicon-th-large"></span> Inicio</a></li>
              <% if @current_empleado.posicion == 'Administrador' %>
              <li class="<%= 'active' if params[:controller] == 'empleados' %>"><a href="/empleados"><span class="glyphicon glyphicon-user"></span> Empleados</a></li>
              <% end %>
              <% if @current_empleado.posicion == 'Administrador' || @current_empleado.posicion == 'Encargado de Almacen' %>
              <li class="<%= 'active' if params[:controller] == 'productos' %>"><a href="/productos"><span class="glyphicon glyphicon-tasks"></span> Productos</a></li>
              <% end %>
              <% if @current_empleado.posicion == 'Administrador' || @current_empleado.posicion == 'Vendedor' %>
              <li class="<%= 'active' if params[:controller] == 'venta' %>"><a href="/venta"><span class="glyphicon glyphicon-shopping-cart"></span> Ventas</a></li>
              <% end %>
              <% if @current_empleado.posicion == 'Administrador' %>
              <li class="dropdown <%= 'active' if params[:controller] == 'reportes' %>"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-list-alt"></span> Reportes</a>
                <ul class="dropdown-menu">
                  <li><a href="/reportes/ventas">Reportes de Ventas <span class="glyphicon glyphicon-shopping-cart"></span></a></li>
                  <li><a href="/reportes/ganancias">Reportes de Ganancias <span class="glyphicon glyphicon-usd"></span></a></li>
                </ul>
              </li>
              <% end %>
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @current_empleado.nombre %></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Cerrar Session <span class="glyphicon glyphicon-off"></span> '.html_safe, logout_path, method: "delete" %></li>
                </ul>
              </li>
            </ul>
          </div>
    </nav>
<% end %>
<% if logged_in? %>
    <div class="container">
<% end %>
<%= yield %>
<% if logged_in? %>
    </div>
<% end %>
<% if logged_in? %>
    <div id="footer">
      <p>&copy; Farmacia FARMAX 2015 &middot; <a class="link" href="/privacidad">Privacidad</a> &middot;
        <a class="link" href="/terminos">T&#233;rminos de Uso</a>
      </p>
    </div>
<% end %>
</body>
</html>